apiVersion: v1
kind: Service
metadata:
  name: macula-gateway
  namespace: macula-system
  labels:
    app: macula-gateway
spec:
  type: ClusterIP
  selector:
    app: macula-gateway
  ports:
  - name: quic
    port: 9443
    targetPort: 9443
    protocol: UDP
  - name: http
    port: 9443
    targetPort: 9443
    protocol: TCP
